# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-04 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foco1', models.BooleanField()),
                ('foco2', models.BooleanField()),
                ('foco3', models.BooleanField()),
                ('foco4', models.BooleanField()),
                ('ventilador', models.BooleanField()),
                ('puerta', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
