# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSuper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
                ('agua', models.BooleanField()),
                ('alcohol', models.CharField(max_length=20)),
                ('corriente1', models.CharField(max_length=20)),
                ('humedad', models.CharField(max_length=20)),
                ('humo', models.BooleanField()),
                ('movimiento', models.CharField(max_length=20)),
                ('temperatura', models.CharField(max_length=20)),
            ],
        ),
    ]
