# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSuper', '0002_sensores'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='reporte',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
