# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-16 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSuper', '0003_sensores_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='alcohol',
        ),
    ]
